### ISSUE TITLE
Update jenkins/docker with Zuhair's latest changes

### ISSUE THREAD

**Issue by warniaha** [zalsader/ceph#100]
Hello,
I [recently](https://github.com/zalsader/ceph/pull/98) merged the latest changes from the ceph main branch into our [add_daos_rgw_sal ](https://github.com/zalsader/ceph/tree/add-daos-rgw-sal)branch. Because of this, if you need to pull from that branch, you'd have to rebuild everything. I updated the [installation guide](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/882638878/DAOS+RGW+DGW+HOWTO) with the latest changes, but here's a summary if you already have the repository. I recommend doing this at the end of your work day since it needs to recompile everything from scratch:

- Install and enable GCC 11: 
cd ~
dnf install gcc-toolset-11 -y 
echo "source scl_source enable gcc-toolset-11" >> ~/.bashrc
source ~/.bashrc

- When compiling DAOS from sources, use the branch libds3 from zalsader/daos, until that branch is merged to main.
git clone --recurse-submodules https://github.com/zalsader/daos.git -b libds3

- ccache will need to be installed from sources:
dnf remove ccache -y
cd ~ 
wget https://github.com/ccache/ccache/releases/download/v4.6.1/ccache-4.6.1.tar.xz
tar -xf ccache-4.6.1.tar.xz
cd ccache-4.6.1/
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_SYSCONFDIR=/etc  -DZSTD_FROM_INTERNET=ON -DHIREDIS_FROM_INTERNET=ON ..
make
make install

- Remove build directory: 
cd ceph
rm -rf build

- Rerun install-deps:
./install-deps.sh

- Continue from [the guide](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/882638878/DAOS+RGW+DGW+HOWTO#Steps) from step 8 as usual.

Sorry for the inconvenience this has caused.
Best, 
Zuhair

**Comment by zalsader** [comment]
@warniaha Did we do anything to update the docker scripts?

**Comment by warniaha** [comment]
yes, I'm testing it now...

**Comment by warniaha** [comment]
yes, I'm testing it now...
