### ISSUE TITLE
Take ownership of jenkins node host

### ISSUE THREAD

**Issue by zalsader** [zalsader/ceph#90]
Jenkins job: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/sv_space/job/rgwdaos-test/
Testing jenkins job: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/sv_space/job/rgwdaos-test-docker/
Jenkins node host: ssc-vm-g3-rhev4-3251.colo.seagate.com
Once Walter leaves, this host will be decommissioned.

Another option is to duplicate the server.  The new server will need to be setup as a Jenkins node.  I contacted Shailesh Vaidya to setup the node.

Also, a passkey will need to be created and credentials for updating the confluence page: https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/1069023297/DAOS+CORTX+S3+tests+results+page

**Comment by trshaffer** [comment]
ssc-vm-g3-rhev4-3251.colo.seagate.com has been transferred to my account, so it won't be decommissioned. I'll look into the API keys next

**Comment by trshaffer** [comment]
Node ownership is transferred, API key is updated to add test results to Confluence through my account
